# AI Context: DTOs (Data Transfer Objects)
# Версия: 1.1.0
# Последнее обновление: 2025-11-28
# Назначение: Структура всех DTOs для use cases

---
# EntryLineDTO
---
EntryLineDTO:
  purpose: "Single line in a double-entry transaction"
  location: py_accountant.application.dto
  used_in:
    - AsyncPostTransaction (input)
    - TransactionDTO (nested in output)

  fields:
    - name: full_name
      type: str
      format: "TYPE:NAME"
      pattern: "^[A-Z0-9]+:[A-Z0-9_]+$"
      example: "ASSET:CASH_USD"
      description: "Account full name"

    - name: debit
      type: Decimal
      serialization: string
      precision: 2
      validation: ">= 0"
      example: "100.00"
      description: "Debit amount (quantized to 2 decimals)"

    - name: credit
      type: Decimal
      serialization: string
      precision: 2
      validation: ">= 0"
      example: "0.00"
      description: "Credit amount (quantized to 2 decimals)"

  invariants:
    - "debit >= 0"
    - "credit >= 0"
    - "NOT (debit > 0 AND credit > 0)"  # One side must be zero

  json_example:
    full_name: "ASSET:CASH_USD"
    debit: "100.00"
    credit: "0.00"

---
# AccountDTO
---
AccountDTO:
  purpose: "Account information"
  location: py_accountant.application.dto
  used_in:
    - AsyncCreateAccount (output)
    - AsyncGetAccount (output)
    - AsyncListAccounts (output list)

  fields:
    - name: full_name
      type: str
      format: "TYPE:NAME"
      example: "ASSET:CASH_USD"
      description: "Account full name"

    - name: account_type
      type: str
      enum: [ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE]
      example: "ASSET"
      description: "Account type"

    - name: name
      type: str
      example: "CASH_USD"
      description: "Account name (without type prefix)"

    - name: currency_code
      type: str
      format: "ISO 4217 or custom"
      example: "USD"
      description: "Currency code"

    - name: metadata
      type: dict
      nullable: true
      example: {"description": "Cash in USD"}
      description: "Optional metadata"

  json_example:
    full_name: "ASSET:CASH_USD"
    account_type: "ASSET"
    name: "CASH_USD"
    currency_code: "USD"
    metadata: null

---
# CurrencyDTO
---
CurrencyDTO:
  purpose: "Currency information"
  location: py_accountant.application.dto
  used_in:
    - AsyncCreateCurrency (output)
    - AsyncGetCurrency (output)
    - AsyncListCurrencies (output list)

  fields:
    - name: code
      type: str
      format: "ISO 4217 or custom (3 chars)"
      example: "USD"
      description: "Currency code"

    - name: name
      type: str
      nullable: true
      example: "US Dollar"
      description: "Currency name"

    - name: is_base_currency
      type: bool
      default: false
      example: true
      description: "Whether this is the base currency"

  json_example:
    code: "USD"
    name: "US Dollar"
    is_base_currency: true

---
# TransactionDTO
---
TransactionDTO:
  purpose: "Complete transaction with all lines"
  location: py_accountant.application.dto
  used_in:
    - AsyncPostTransaction (output)
    - AsyncGetTransaction (output)

  fields:
    - name: transaction_id
      type: int
      example: 123
      description: "Transaction ID"

    - name: posted_at
      type: datetime
      serialization: "ISO8601 UTC"
      example: "2025-11-28T12:00:00+00:00"
      description: "Transaction timestamp"

    - name: memo
      type: str
      example: "Payment for services"
      description: "Transaction memo"

    - name: lines
      type: list[EntryLineDTO]
      min_length: 2
      description: "Transaction lines"

    - name: meta
      type: dict
      nullable: true
      example: {"idempotency_key": "tx-001"}
      description: "Optional metadata"

  invariants:
    - "len(lines) >= 2"
    - "sum(line.debit for line in lines) == sum(line.credit for line in lines)"

  json_example:
    transaction_id: 123
    posted_at: "2025-11-28T12:00:00+00:00"
    memo: "Payment for services"
    lines:
      - full_name: "ASSET:CASH_USD"
        debit: "100.00"
        credit: "0.00"
      - full_name: "REVENUE:SERVICES"
        debit: "0.00"
        credit: "100.00"
    meta:
      idempotency_key: "tx-001"

---
# BalanceDTO
---
BalanceDTO:
  purpose: "Account balance at a point in time"
  location: py_accountant.application.dto
  used_in:
    - AsyncGetBalance (output)

  fields:
    - name: full_name
      type: str
      example: "ASSET:CASH_USD"
      description: "Account full name"

    - name: currency_code
      type: str
      example: "USD"
      description: "Currency code"

    - name: debit
      type: Decimal
      serialization: string
      precision: 2
      example: "1000.00"
      description: "Total debit"

    - name: credit
      type: Decimal
      serialization: string
      precision: 2
      example: "500.00"
      description: "Total credit"

    - name: net
      type: Decimal
      serialization: string
      precision: 2
      example: "500.00"
      description: "Net balance (debit - credit)"

    - name: as_of
      type: datetime
      nullable: true
      serialization: "ISO8601 UTC"
      example: "2025-11-28T12:00:00+00:00"
      description: "Balance as of timestamp"

  json_example:
    full_name: "ASSET:CASH_USD"
    currency_code: "USD"
    debit: "1000.00"
    credit: "500.00"
    net: "500.00"
    as_of: "2025-11-28T12:00:00+00:00"

---
# TradingBalanceRawDTO
---
TradingBalanceRawDTO:
  purpose: "Raw trading balance (no FX conversion)"
  location: py_accountant.application.dto
  used_in:
    - AsyncGetTradingBalanceRaw (output list item)

  fields:
    - name: currency_code
      type: str
      example: "USD"
      description: "Currency code"

    - name: debit
      type: Decimal
      serialization: string
      precision: 2
      example: "1000.00"
      description: "Total debit across all ASSET accounts"

    - name: credit
      type: Decimal
      serialization: string
      precision: 2
      example: "500.00"
      description: "Total credit across all ASSET accounts"

    - name: net
      type: Decimal
      serialization: string
      precision: 2
      example: "500.00"
      description: "Net balance (debit - credit)"

  json_example:
    currency_code: "USD"
    debit: "1000.00"
    credit: "500.00"
    net: "500.00"

---
# TradingBalanceDetailedDTO
---
TradingBalanceDetailedDTO:
  purpose: "Trading balance with FX conversion to base currency"
  location: py_accountant.application.dto
  used_in:
    - AsyncGetTradingBalanceDetailed (output list item)

  fields:
    - name: currency_code
      type: str
      example: "EUR"
      description: "Original currency code"

    - name: base_currency_code
      type: str
      example: "USD"
      description: "Base currency code"

    - name: debit
      type: Decimal
      serialization: string
      precision: 2
      example: "1000.00"
      description: "Total debit (original currency)"

    - name: credit
      type: Decimal
      serialization: string
      precision: 2
      example: "500.00"
      description: "Total credit (original currency)"

    - name: net
      type: Decimal
      serialization: string
      precision: 2
      example: "500.00"
      description: "Net balance (original currency)"

    - name: used_rate
      type: Decimal
      serialization: string
      precision: 6
      example: "1.250000"
      description: "Exchange rate used (1.0 for base currency)"

    - name: debit_base
      type: Decimal
      serialization: string
      precision: 2
      example: "1250.00"
      description: "Debit in base currency"

    - name: credit_base
      type: Decimal
      serialization: string
      precision: 2
      example: "625.00"
      description: "Credit in base currency"

    - name: net_base
      type: Decimal
      serialization: string
      precision: 2
      example: "625.00"
      description: "Net balance in base currency"

  invariants:
    - "For base_currency: used_rate = 1.0"
    - "For non-base: used_rate > 0 (must exist)"
    - "debit_base = debit * used_rate (quantized to 2)"
    - "credit_base = credit * used_rate (quantized to 2)"
    - "net_base = net * used_rate (quantized to 2)"

  json_example:
    currency_code: "EUR"
    base_currency_code: "USD"
    debit: "1000.00"
    credit: "500.00"
    net: "500.00"
    used_rate: "1.250000"
    debit_base: "1250.00"
    credit_base: "625.00"
    net_base: "625.00"

---
# ExchangeRateEventDTO
---
ExchangeRateEventDTO:
  purpose: "Exchange rate event (audit trail)"
  location: py_accountant.application.dto
  used_in:
    - AsyncPostExchangeRateEvent (output)
    - AsyncListExchangeRateEvents (output list item)

  fields:
    - name: event_id
      type: int
      nullable: true
      example: 123
      description: "Event ID (null before persistence)"

    - name: currency_code
      type: str
      example: "EUR"
      description: "Currency code"

    - name: rate
      type: Decimal
      serialization: string
      precision: 6
      validation: "> 0"
      example: "1.250000"
      description: "Exchange rate (quantized to 6 decimals)"

    - name: recorded_at
      type: datetime
      serialization: "ISO8601 UTC"
      example: "2025-11-28T12:00:00+00:00"
      description: "Event timestamp"

    - name: source
      type: str
      nullable: true
      example: "ECB API"
      description: "Rate source"

  invariants:
    - "rate > 0"

  json_example:
    event_id: 123
    currency_code: "EUR"
    rate: "1.250000"
    recorded_at: "2025-11-28T12:00:00+00:00"
    source: "ECB API"

---
# FxTTLPlanDTO
---
FxTTLPlanDTO:
  purpose: "FX audit TTL plan (before execution)"
  location: py_accountant.application.dto
  used_in:
    - AsyncPlanFxAuditTTL (output)

  fields:
    - name: cutoff
      type: datetime
      serialization: "ISO8601 UTC"
      example: "2025-08-29T00:00:00+00:00"
      description: "Cutoff timestamp (events older will be processed)"

    - name: mode
      type: str
      enum: [delete, archive]
      example: "archive"
      description: "TTL mode"

    - name: retention_days
      type: int
      example: 90
      description: "Retention period in days"

    - name: batch_size
      type: int
      example: 1000
      description: "Batch size for processing"

    - name: dry_run
      type: bool
      example: true
      description: "Whether this is a dry run"

    - name: total_old
      type: int
      example: 12345
      description: "Total old events count"

    - name: batches
      type: list[dict]
      example: [{"offset": 0, "limit": 1000}, {"offset": 1000, "limit": 1000}]
      description: "Batch plan (offset/limit pairs)"

    - name: old_event_ids
      type: list[int]
      example: [1, 2, 3, 4, 5]
      description: "Sample old event IDs"

  json_example:
    cutoff: "2025-08-29T00:00:00+00:00"
    mode: "archive"
    retention_days: 90
    batch_size: 1000
    dry_run: true
    total_old: 12345
    batches:
      - offset: 0
        limit: 1000
      - offset: 1000
        limit: 1000
    old_event_ids: [1, 2, 3, 4, 5]

---
# Serialization Rules
---
serialization_rules:
  decimal_to_json:
    rule: "Convert Decimal to string"
    example: 'Decimal("100.00") → "100.00"'

  datetime_to_json:
    rule: "ISO8601 UTC format"
    format: "YYYY-MM-DDTHH:MM:SS+00:00 or YYYY-MM-DDTHH:MM:SSZ"
    example: '"2025-11-28T12:00:00+00:00"'

  json_keys:
    rule: "snake_case"
    example: 'full_name, currency_code, is_base_currency'

---
# Validation Patterns
---
validation_patterns:
  full_name:
    pattern: "^[A-Z0-9]+:[A-Z0-9_]+$"
    example: "ASSET:CASH_USD"

  currency_code:
    pattern: "^[A-Z]{3}$"
    example: "USD"

  account_type:
    enum: [ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE]

  amounts:
    rule: "Quantized to 2 decimals, >= 0"
    example: "100.00"

  rates:
    rule: "Quantized to 6 decimals, > 0"
    example: "1.250000"
