@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam activityArrowColor Black
skinparam activityBorderColor Black
skinparam activityBackgroundColor White
skinparam defaultFontName monospace
start
:Вход options (startDate?, endDate?);
:Установить значения по умолчанию\n start=Epoch, end=now(UTC);
:Инициализировать результат\n result.currency={}, base=0;
:Выбрать все currencies;
repeat
  :Взять валюту C;
  partition DB {
    :credits_sum(C) = SUM(amount)\nJOIN Transaction->Account\nWHERE Account.currency=C \nAND credit=true \nAND createdAt BETWEEN [start,end];
    :debits_sum(C) = SUM(amount)\nJOIN Transaction->Account\nWHERE Account.currency=C \nAND credit=false \nAND createdAt BETWEEN [start,end];
  }
  :diff = debits_sum - credits_sum;
  :result.currency[C.code] = str(diff);
  if (C.id == 1?) then (да)
    :rate = 1.0;
  else (нет)
    :rate = C.exchange_rate;
  endif
  :base = base + diff / rate;
repeat while (есть ещё валюты?) is (да)
:result.base = str(round(base));
:Вернуть { currency: map, base: str };
stop
@enduml